namespace RayaTrainer.Core.Agent;

public enum AgentCommand : ushort
{
    Ping = 1,
    GetStatus = 2,
    InstallPatches = 3,
    RestorePatches = 4,
    SetToggle = 5,
    TriggerAction = 6,
    WriteResourceValues = 7,
    ReadSelectedUnitCode = 8,
    ReadMemory = 9,
    SmokeGetThingClass = 10,
    LevelUpSelected = 11,
    CreateUnit = 12,
    KillUnit = 13,
    CopyForMe = 14,
    GetMeBase = 15,
    WeNeedBack = 16,
    SetUnitState = 17,
    GetCurrentPlayer = 18,
    LookupScienceByHash = 19,
    GrantPlayerTech = 20,
    GrantUpgradeToPlayer = 21,
    HasUpgrade = 22,
    LookupTemplateByHash = 23,
    LookupUpgradeByHash = 24,
    GrantSecretProtocol = 25,
    GrantSelectedUpgrade = 26,
    ClearPlayerTechLocks = 27,
    SecretProtocolBindingProbe = 28,
    ReplaceTemplateModel = 29,
    ReplaceTemplateWeapon = 30,
    SetSelectedStatusBit = 31,
    SetSelectedUnitHealth = 32,
    SetNativeCatalog = 33,
    GetMismatchDiagnostics = 34,
    ScanSignatures = 35,
    GetGameMode = 36,
    ExpandProductionQueue = 37,
    TeleportSelectedUnitsToMouse = 38,
    SetSelectedUnitSpeed = 39,
    CaptureSelectedUnits = 40,
    SetSelectedUnitAmmo = 41,
    ToggleSelectedAttackSpeed = 42,
    ToggleSelectedAttackRange = 43,
    ClearSelectedAttackSpeedEffects = 44,
    ClearSelectedAttackRangeEffects = 45
}
